import Head from 'next/head'
import React from 'react'
import CTA from '../../components/cta'
import { useBreakpoint } from '../../util/use-breakpoint'

function PrivacyPolicy() {
	return (
		<main id='Privacy Policy' className={`mosafe-section`}>
			<Head>
				<title>Privacy Policy</title>
				<meta name='description' content='Work safety and securely, knowing that Mosafe protects your data, manages your users and utilises best practices in storing your information.'></meta>
				<meta name='keywords' content='Mosafe privacy policy, Mosafe data storage, Mosafe privacy' />
			</Head>
			<h1 className='text-[38px] font-black mb-4'>Privacy Policy</h1>
			<p className='mb-12 text-[24px]'>We take your privacy very seriously. Please read below to find out how we protect your data.</p>
			<p className='legal-h5'>Last updated May 27, 2022</p>
			<p className='legal-body'>
				This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the
				Service and tells You about Your privacy rights and how the law protects You.
			</p>

			<p className='legal-body'>
				We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information
				in accordance with this Privacy Policy.
			</p>

			<h2 className='legal-h3'>Interpretation and Definitions</h2>

			<p className='legal-h4'>Interpretation</p>

			<p className='legal-body'>
				The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions
				shall have the same meaning regardless of whether they appear in singular or in plural.
			</p>

			<p className='legal-h4'>Definitions</p>

			<p className='legal-body'>For the purposes of this Privacy Policy:</p>

			<p className='legal-body'>
				<span className='font-bold'>Account</span> means a unique account created for You to access our Service or parts of our Service.
			</p>
			<p className='legal-body'>
				<span className='font-bold'>Affiliate</span> means an entity that controls, is controlled by or is under common control with a party,
				where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for
				election of directors or other managing authority.
			</p>
			<p className='legal-body'>
				<span className='font-bold'>Application</span> means the software program provided by the Company downloaded by You on any electronic
				device, named Mosafe
			</p>
			<p className='legal-body'>
				<span className='font-bold'>Company</span> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or
				&quot;Our&quot; in this Agreement) refers to Beeston Enterprises PTY LTD, Millers Lane, Coorparoo, Brisbane Q 4151.
			</p>
			<p className='legal-body'>
				<span className='font-bold'>Cookies</span> are small files that are placed on Your computer, mobile device or any other device by a
				website, containing the details of Your browsing history on that website among its many uses.
			</p>
			<p className='legal-body'>
				<span className='font-bold'>Country</span> refers to: Queensland, Australia
			</p>
			<p className='legal-body'>
				<span className='font-bold'>Device</span> means any device that can access the Service such as a computer, a cellphone or a digital
				tablet.
			</p>
			<p className='legal-body'>
				<span className='font-bold'>Personal Data</span> is any information that relates to an identified or identifiable inpidual.
			</p>
			<p className='legal-body'>
				<span className='font-bold'>Service</span> refers to the Application or the Website or both.
			</p>
			<p className='legal-body'>
				<span className='font-bold'>Service Provider</span> means any natural or legal person who processes the data on behalf of the Company.
				It refers to third-party companies or inpiduals employed by the Company to facilitate the Service, to provide the Service on behalf of
				the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
			</p>
			<p className='legal-body'>
				<span className='font-bold'>Third-party Social Media Service</span> refers to any website or any social network website through which a
				User can log in or create an account to use the Service.
			</p>
			<p className='legal-body'>
				<span className='font-bold'>Usage Data</span> refers to data collected automatically, either generated by the use of the Service or from
				the Service infrastructure itself (for example, the duration of a page visit).
			</p>
			<p className='legal-body'>
				<span className='font-bold'>Website</span> refers to Mosafe, accessible from{' '}
				<a href='https://www.mosafe.com.au' target='_blank' rel='noreferrer' className='text-link-base cursor-pointer underline'>
					www.mosafe.com.au
				</a>
			</p>
			<p className='legal-body'>
				<span className='font-bold'>You</span> means the inpidual accessing or using the Service, or the company, or other legal entity on
				behalf of which such inpidual is accessing or using the Service, as applicable.
			</p>

			<h2 className='legal-h3'>Collecting and Using Your Personal Data</h2>

			<p className='legal-h4'>Types of Data Collected</p>

			<p className='legal-h5'>Personal Data</p>

			<p className='legal-body'>
				While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or
				identify You. Personally identifiable information may include, but is not limited to:
			</p>

			<p>Email address</p>
			<p>First name and last name</p>
			<p>Phone number</p>
			<p>Address, State, Province, ZIP/Postal code, City</p>
			<p className='mb-4'>Usage Data</p>

			<p className='legal-h5'>Usage Data</p>

			<p className='legal-body'>Usage Data is collected automatically when using the Service.</p>

			<p className='legal-body'>
				Usage Data may include information such as Your Device&#39;s Internet Protocol address (e.g. IP address), browser type, browser version,
				the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and
				other diagnostic data. When You access the Service by or through a mobile device, We may collect certain information automatically,
				including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device,
				Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
			</p>

			<p className='legal-body'>
				We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a
				mobile device.
			</p>

			<p className='legal-h5'>Information from Third-Party Social Media Services</p>

			<p className='legal-body'>
				The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:
			</p>

			<p>Google</p>
			<p>Facebook</p>
			<p>Twitter</p>
			<p className='mb-4'>LinkedIn</p>

			<p className='legal-body'>
				If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that
				is already associated with Your Third-Party Social Media Service&#39;s account, such as Your name, Your email address, Your activities
				or Your contact list associated with that account.
			</p>

			<p className='legal-body'>
				You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service&#39;s
				account. If You choose to provide such information and Personal Data, during registration or otherwise, You are giving the Company
				permission to use, share, and store it in a manner consistent with this Privacy Policy.
			</p>

			<p className='legal-h5'>Information Collected while Using the Application</p>

			<p className='legal-body'>
				While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:
			</p>

			<p className='legal-body'>
				Information regarding your location Pictures and other information from your Device&#39;s camera and photo library
			</p>

			<p className='legal-body'>
				We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the
				Company&#39;s servers and/or a Service Provider&#39;s server or it may be simply stored on Your device.
			</p>

			<p className='legal-body'>You can enable or disable access to this information at any time, through Your Device settings.</p>

			<p className='legal-h5'>Tracking Technologies and Cookies</p>

			<p className='legal-body'>
				We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking
				technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The
				technologies We use may include:
			</p>

			<p className='legal-body'>
				<span className='font-bold'>Cookies or Browser Cookies.</span> A cookie is a small file placed on Your Device. You can instruct Your
				browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to
				use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use
				Cookies.
			</p>
			<p className='legal-body'>
				<span className='font-bold'>Flash Cookies.</span> Certain features of our Service may use local stored objects (or Flash Cookies) to
				collect and store information about Your preferences or Your activity on our Service. Flash Cookies are not managed by the same browser
				settings as those used for Browser Cookies. For more information on how You can delete Flash Cookies, please read &quot;Where can I
				change the settings for disabling, or deleting local shared objects?&quot; available{' '}
				<a
					href='https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_'
					target='_blank'
					rel='noreferrer'
					className='text-link-base cursor-pointer underline'>
					here
				</a>
			</p>
			<p className='legal-body'>
				<span className='font-bold'>Web Beacons.</span> Certain sections of our Service and our emails may contain small electronic files known
				as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users
				who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a
				certain section and verifying system and server integrity).
			</p>

			<p className='legal-body'>
				Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile
				device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. You can learn more about cookies
				here: Cookies by TermsFeed Generator.
			</p>

			<p className='legal-body'>We use both Session and Persistent Cookies for the purposes set out below:</p>

			<p className='legal-h5'>Necessary / Essential Cookies</p>

			<p className='legal-body'>Type: Session Cookies</p>

			<p className='legal-body'>Administered by: Us</p>

			<p className='legal-body'>
				Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its
				features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have
				asked for cannot be provided, and We only use these Cookies to provide You with those services.
			</p>

			<p className='legal-h5'>Cookies Policy / Notice Acceptance Cookies</p>

			<p className='legal-body'>Type: Persistent Cookies</p>

			<p className='legal-body'>Administered by: Us</p>

			<p className='legal-body'>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>

			<p className='legal-h5'>Functionality Cookies</p>

			<p className='legal-body'>Type: Persistent Cookies</p>

			<p className='legal-body'>Administered by: Us</p>

			<p className='legal-body'>
				Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or
				language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter
				your preferences every time You use the Website.
			</p>

			<p className='legal-h5'>Tracking and Performance Cookies</p>

			<p className='legal-body'>Type: Persistent Cookies</p>

			<p className='legal-body'>Administered by: Third-Parties</p>

			<p className='legal-body'>
				Purpose: These Cookies are used to track information about traffic to the Website and how users use the Website. The information
				gathered via these Cookies may directly or indirectly identify you as an inpidual visitor. This is because the information collected is
				typically linked to a pseudonymous identifier associated with the device you use to access the Website. We may also use these Cookies to
				test new pages, features or new functionality of the Website to see how our users react to them.
			</p>

			<p className='legal-body'>
				For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section
				of our Privacy Policy.
			</p>

			<p className='legal-h4'>Use of Your Personal Data</p>

			<p className='legal-body'>The Company may use Personal Data for the following purposes:</p>

			<p className='legal-body'>
				<span className='font-bold'>To provide and maintain our Service,</span> including to monitor the usage of our Service.
			</p>

			<p className='legal-body'>
				<span className='font-bold'>To manage Your Account:</span> to manage Your registration as a user of the Service. The Personal Data You
				provide can give You access to different functionalities of the Service that are available to You as a registered user.
			</p>

			<p className='legal-body'>
				<span className='font-bold'>For the performance of a contract:</span> the development, compliance and undertaking of the purchase
				contract for the products, items or services You have purchased or of any other contract with Us through the Service.
			</p>

			<p className='legal-body'>
				<span className='font-bold'>To contact You:</span> To contact You by email, telephone calls, SMS, or other equivalent forms of
				electronic communication, such as a mobile application&#39;s push notifications regarding updates or informative communications related
				to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their
				implementation.
			</p>

			<p className='legal-body'>
				<span className='font-bold'>To provide You</span> with news, special offers and general information about other goods, services and
				events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive
				such information. To manage Your requests: To attend and manage Your requests to Us.
			</p>

			<p className='legal-body'>
				<span className='font-bold'>For business transfers:</span> We may use Your information to evaluate or conduct a merger, pestiture,
				restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as
				part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets
				transferred.
			</p>

			<p className='legal-body'>
				<span className='font-bold'>For other purposes:</span> We may use Your information for other purposes, such as data analysis,
				identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products,
				services, marketing and your experience.
			</p>

			<p className='legal-body'>We may share Your personal information in the following situations:</p>

			<p className='legal-body'>
				<span className='font-bold'>With Service Providers:</span> We may share Your personal information with Service Providers to monitor and
				analyze the use of our Service, for payment processing, to contact You.
			</p>

			<p className='legal-body'>
				<span className='font-bold'>For business transfers:</span> We may share or transfer Your personal information in connection with, or
				during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another
				company.
			</p>

			<p className='legal-body'>
				<span className='font-bold'>With Affiliates:</span> We may share Your information with Our affiliates, in which case we will require
				those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners
				or other companies that We control or that are under common control with Us.
			</p>

			<p className='legal-body'>
				<span className='font-bold'>With business partners:</span> We may share Your information with Our business partners to offer You certain
				products, services or promotions.
			</p>

			<p className='legal-body'>
				<span className='font-bold'>With other users:</span> when You share personal information or otherwise interact in the public areas with
				other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or
				register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see Your name, profile,
				pictures and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with
				You and view Your profile.
			</p>

			<p className='legal-body'>
				<span className='font-bold'>With Your consent:</span> We may disclose Your personal information for any other purpose with Your consent.
			</p>

			<p className='legal-h4'>Retention of Your Personal Data</p>

			<p className='legal-body'>
				The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will
				retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to
				retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
			</p>

			<p className='legal-body'>
				The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time,
				except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to
				retain this data for longer time periods.
			</p>

			<p className='legal-h4'>Transfer of Your Personal Data</p>

			<p className='legal-body'>
				Your information, including Personal Data, is processed at the Company&#39;s operating offices and in any other places where the parties
				involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located
				outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from
				Your jurisdiction.
			</p>

			<p className='legal-body'>
				Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
			</p>

			<p className='legal-body'>
				The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy
				Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place
				including the security of Your data and other personal information.
			</p>

			<p className='legal-h4'>Disclosure of Your Personal Data</p>

			<p className='legal-h5'>Business Transactions</p>

			<p className='legal-body'>
				If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before
				Your Personal Data is transferred and becomes subject to a different Privacy Policy.
			</p>

			<p className='legal-h5'>Law enforcement</p>

			<p className='legal-body'>
				Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to
				valid requests by public authorities (e.g. a court or a government agency).
			</p>

			<p className='legal-h5'>Other legal requirements</p>

			<p className='legal-body'>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>

			<p>Comply with a legal obligation</p>
			<p>Protect and defend the rights or property of the Company</p>
			<p>Prevent or investigate possible wrongdoing in connection with the Service</p>
			<p>Protect the personal safety of Users of the Service or the public</p>
			<p className='mb-4'>Protect against legal liability</p>

			<p className='legal-h5'>Security of Your Personal Data</p>

			<p className='legal-body'>
				The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of
				electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot
				guarantee its absolute security.
			</p>

			<h2 className='legal-h3'>Detailed Information on the Processing of Your Personal Data</h2>

			<p className='legal-body'>
				The Service Providers We use may have access to Your Personal Data. These third-party vendors collect, store, use, process and transfer
				information about Your activity on Our Service in accordance with their Privacy Policies.
			</p>

			<p className='legal-h4'>Analytics</p>

			<p className='legal-body'>We may use third-party Service providers to monitor and analyze the use of our Service.</p>

			<p className='legal-h5'>Google Analytics</p>

			<p className='legal-body'>
				Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to
				track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to
				contextualize and personalize the ads of its own advertising network.
			</p>

			<p className='legal-body'>
				You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out
				browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js and dc.js) from sharing information with Google
				Analytics about visits activity.
			</p>

			<p className='legal-body'>
				You may opt-out of certain Google Analytics features through your mobile device settings, such as your device advertising settings or by
				following the instructions provided by Google in their Privacy Policy:{' '}
				<a href='https://policies.google.com/privacy' target='_blank' rel='noreferrer' className='text-link-base cursor-pointer underline'>
					policies.google.com/privacy
				</a>
			</p>

			<p className='legal-body'>
				For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page:{' '}
				<a href='https://policies.google.com/privacy' target='_blank' rel='noreferrer' className='text-link-base cursor-pointer underline'>
					policies.google.com/privacy
				</a>
			</p>

			<p className='legal-h4'>Email Marketing</p>

			<p className='legal-body'>
				We may use Your Personal Data to contact You with newsletters, marketing or promotional materials and other information that may be of
				interest to You. You may opt-out of receiving any, or all, of these communications from Us by following the unsubscribe link or
				instructions provided in any email We send or by contacting Us.
			</p>

			<p className='legal-body'>We may use Email Marketing Service Providers to manage and send emails to You.</p>

			<p className='legal-h5'>AWS</p>

			<p className='legal-body'>
				Their Privacy Policy can be viewed at{' '}
				<a
					href='https://aws.amazon.com/compliance/data-privacy/'
					target='_blank'
					rel='noreferrer'
					className='text-link-base cursor-pointer underline'>
					aws.amazon.com/compliance/data-privacy/
				</a>
			</p>

			<p className='legal-h4'>Payments</p>

			<p className='legal-body'>
				We may provide paid products and/or services within the Service. In that case, we may use third-party services for payment processing
				(e.g. payment processors).
			</p>

			<p className='legal-body'>
				We will not store or collect Your payment card details. That information is provided directly to Our third-party payment processors
				whose use of Your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by
				PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and
				Discover. PCI-DSS requirements help ensure the secure handling of payment information.
			</p>

			<p className='legal-h5'>Stripe</p>

			<p className='legal-body'>
				Their Privacy Policy can be viewed at{' '}
				<a href='https://stripe.com/us/privacy' target='_blank' rel='noreferrer' className='text-link-base cursor-pointer underline'>
					stripe.com/us/privacy
				</a>
			</p>

			<p className='legal-h4'>Children&#39;s Privacy</p>

			<p className='legal-body'>
				Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone
				under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please
				contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental
				consent, We take steps to remove that information from Our servers.
			</p>

			<p className='legal-body'>
				If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may
				require Your parent&#39;s consent before We collect and use that information.
			</p>

			<p className='legal-h4'>Links to Other Websites</p>

			<p className='legal-body'>
				Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to
				that third party&#39;s site. We strongly advise You to review the Privacy Policy of every site You visit.
			</p>

			<p className='legal-body'>
				We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or
				services.
			</p>

			<p className='legal-h4'>Changes to this Privacy Policy</p>

			<p className='legal-body'>
				We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
			</p>

			<p className='legal-body'>
				We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the
				&quot;Last updated&quot; date at the top of this Privacy Policy.
			</p>

			<p className='legal-body'>
				You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are
				posted on this page.
			</p>

			<p className='legal-h4'>Contact Us</p>

			<p className='legal-body'>
				If you have any questions about this Privacy Policy, You can contact us: By email:{' '}
				<a href='mailto::privacy@mosafe.com.au' target='_blank' rel='noreferrer' className='text-link-base cursor-pointer underline'>
					privacy@mosafe.com.au
				</a>
			</p>

			<CTA />
		</main>
	)
}

export default PrivacyPolicy
